### PR TITLE
Hot reload ssr

### PR DESCRIPTION
**Pull request by codingfriend1**
Breaks the separated api server and hot-reload-feathers-ssr quasar template into it's own server file.

### CODE REVIEW

**Comment by claustres** [comment]
Thanks very much to have separated. When I try to run it on my side I get this *Error with SSR: ReferenceError: navigator is not defined* with following call stack:
```
at getUserAgent (node_modules/quasar-framework/dist/quasar.esm.js:10:0)
at getPlatform (node_modules/quasar-framework/dist/quasar.esm.js:56:0)
at Object.module.exports.Object.defineProperty.value (node_modules/quasar-framework/dist/quasar.esm.js:168:0)
at __webpack_require__ (webpack:/webpack/bootstrap 85df0fb5560a90ec9f99:25:0)
at Object.module.exports.Object.defineProperty.value (src/main.js:14:0)
at __webpack_require__ (webpack:/webpack/bootstrap 85df0fb5560a90ec9f99:25:0)
at app.js:20344:28
at F (D:\Development\qf-ssr\node_modules\core-js\library\modules\_export.js:35:28)
at module.exports.module.exports (src/server-entry.js:3:9)
at D:\Development\qf-ssr\node_modules\vue-server-renderer\build.js:5894:15
at D:\Development\qf-ssr\node_modules\vue-server-renderer\build.js:5870:14
at Object.renderToString (D:\Development\qf-ssr\node_modules\vue-server-renderer\build.js:6022:9)
at renderHtml (D:\Development\qf-ssr\api\src\ssr.js:100:14)
at readyPromise.then (D:\Development\qf-ssr\api\src\ssr.js:111:29)
at process._tickCallback (internal/process/next_tick.js:103:7)
```

I simply ran like that, let me know if I miss something:
```
quasar init @claustres/quasar-templates#feathers-api-ssr quasar-feathers-ssr
cd quasar-feathers-ssr
npm/yarn install
quasar build
quasar init @quasarframework/quasar-wrapper-feathersjs-api#ssr api
cd api
npm/yarn install
npm run prod
```

**Comment by codingfriend1** [comment]
Thanks for testing, that's a problem with the quasar framework and I've added a pull request to quasar that fixes it. "Makes quasar ssr friendly."

Once that's merged, it should work.

**Comment by codingfriend1** [comment]
I got rid of the hacky solution of mocking the browser.

**Comment by claustres** [comment]
OK good to know, I merge for now and will test once quasar PR has been merged.

**Comment by codingfriend1** [comment]
Turns out there's more to the isomorphic app than just protecting a few calls. There's a number of elements that render based on the platform that don't render when on the server causing hydration errors. For instance q-btn or q-context-menu.

I'm beginning work on a quasar ssr test environment but I'm not familiar enough with the configs to be effective. I could use some help getting the test environment setup. I've got a basic boilerplate started. You just need to run `node server.js`

https://github.com/codingfriend1/quasar/tree/ssr

**Pull request merged**
