### PR TITLE
SSR

### PR DESCRIPTION
**Pull request by codingfriend1**
Adds server side rendering. Reduces feathersjs to just the boilerplate generated by feathers-cli except for ssr and statics files and vue-server-side-rendering.js.

Does not include some of the proxying features. Debug mode is not working. SSR during `quasar dev` is not working. Only serving dist folder production code will work with SSR.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

Removes nedb, message and users services and leaves blank feathersjs boilerplate generated from the feathers-cli. Adds new ssr and statics middleware.

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all Quasar themes
- [x] Any necessary documentation has been added or updated [in the docs](https://github.com/quasarframework/quasar-framework.org/tree/master/source) (for faster update click on "Suggest an edit on GitHub" at bottom of page) or explained in the PR's description.

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by 3kynox** [comment]
Woah, great first SSR integration. Looks great !

**Comment by claustres** [comment]
Thanks for your PR, I succeeded in make it run on my config, I had only to fix small issues.

What I propose is to start a new branch for this so that:
* the wrapper might exist in different flavors, SSR being one (indeed your PR removes a lot of interesting things from the initial code)
* we can work on improving it without affecting other flavors

The thing that needs to be fixed before it is really ready IMHO it to makes dev mode work, forcing `NODE_ENV` to `production` when launchin dev mode is not so clean. Let discuss about that.

**Comment by claustres** [comment]
By the way I tested it using your repo https://github.com/codingfriend1/quasar-feathers-ssr and did not realize your PR is slightly different, notably about running the dev mode. I should have a look at it but cannot for now, I will let you know about any remark.

Thanks again

**Comment by claustres** [comment]
Added a link to the SSR flavor in the README: https://github.com/quasarframework/quasar-wrapper-feathersjs-api/blob/dev/README.md.

**Comment by codingfriend1** [comment]
Thanks!

Re-pull down the main branch to see a working example. I had to remake the repo.

https://github.com/codingfriend1/quasar-feathers-ssr

Or clone: https://github.com/codingfriend1/quasar-feathers-ssr.git

npm install in both api and root.

quasar run build

export PORT=3030

npm run dev in api folder

Debug mode should be working. I could use help with getting ssr working while in dev mode. The way the build system works will require some bigger changes to get it working. This will require coordination with the quasar-default-template, unless we build our own template.

**Comment by codingfriend1** [comment]
Keep in mind this ssr branch requires changes in the quasar default template. Primarily the build system, main.js, and routes.js.

**Comment by codingfriend1** [comment]
It may be worth starting our own quasar template. A ssr template that will have this api preinstalled as well as the changes need in the default template.

**Comment by claustres** [comment]
Yes that's the purpose of https://github.com/claustres/quasar-templates. Will create you a branch when i will be back to my laptop.

**Comment by claustres** [comment]
Just created https://github.com/claustres/quasar-templates/tree/feathers-api-ssr, feel free to PR. Also updated README, feel free to PR as well as required.

**Comment by codingfriend1** [comment]
I've submitted a pull request.

There are a couple problems with running SSR rendering while in quasar dev mode.

1. It's an extra compilation step, slowing down turn around. Quasar dev would actually have to output files for the server to read instead of doing everything in memory. At least for SSR to work we need an index.html page, a css page, and a script to our development .js file.
2. It may mess up hot reload. I am not strong in webpack, so perhaps you know of a way to get both working.
3. Is it necessary to test ssr while in development?

**Comment by claustres** [comment]
For dev I have a similar issue with the cordova wrapper that requires first the client app to be bundled. What I suggest is to add an option so that we can call something like `quasar prod --debug` to have at least unminified/unobfuscated version of the code that can be debugged when required.

I will have a look into this.

**Pull request merged**
